# Generated by Django 5.1.4 on 2024-12-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='images/Portrait', upload_to='images/profile-pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Bio', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
