# Generated by Django 5.1.4 on 2024-12-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0002_user_profilepic_alter_user_bio_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='../../images/Portrait', upload_to='images/profile-pics'),
        ),
    ]
