# Generated by Django 5.1.4 on 2024-12-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0003_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='DatabaseAssets/images/profilePics/Portrait.png', upload_to='DatabaseAssets/images/profilePics'),
        ),
    ]
