# Generated by Django 5.1.4 on 2024-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0004_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='profilePics/Portrait.png', upload_to='profilePics'),
        ),
    ]
