# Generated by Django 5.1.4 on 2024-12-18 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0007_post_body_post_post_date_post_title_post_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 23, 41, 3, 82858)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 23, 41, 3, 82858)),
        ),
    ]
