# Generated by Django 5.1.4 on 2024-12-18 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0009_alter_post_author_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 11, 17, 5, 216376)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 11, 17, 5, 216376)),
        ),
    ]
