# Generated by Django 5.1.4 on 2024-12-18 22:11

import HeckWebApp.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0011_alter_post_author_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 15, 11, 52, 718227)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 15, 11, 52, 718227)),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, unique=True, upload_to=HeckWebApp.models.upload_to_date_directory)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeckWebApp.post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
