# Generated by Django 5.1.4 on 2024-12-19 17:57

import HeckWebApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0012_alter_post_body_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 10, 57, 16, 899619)),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 10, 57, 16, 899619)),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=HeckWebApp.models.upload_to_date_directory),
        ),
    ]
