# Generated by Django 5.1.4 on 2024-12-19 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0018_alter_post_post_date_alter_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='postPics\\2024\\12\\19'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 11, 28, 31, 432654)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 11, 28, 31, 432654)),
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
