# Generated by Django 5.1.4 on 2024-12-19 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0019_post_image_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 14, 37, 9, 127922)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 14, 37, 9, 127922)),
        ),
    ]
