# Generated by Django 5.1.4 on 2024-12-19 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0020_alter_post_post_date_alter_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 15, 38, 45, 304783)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 15, 38, 45, 304783)),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown0', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='unknown', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='profilePics/Portrait.png', unique=True, upload_to='profilePics'),
        ),
    ]
