# Generated by Django 5.1.4 on 2024-12-19 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0022_alter_post_post_date_alter_post_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 16, 6, 28, 818536)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 16, 6, 28, 818536)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='profilePics/Portrait.png', upload_to='profilePics\\<django.db.models.query_utils.DeferredAttribute object at 0x000001BE13CEEF30>'),
        ),
    ]
