# Generated by Django 5.1.4 on 2024-12-20 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0028_alter_post_post_date_alter_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 14, 54, 9, 980049)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 14, 54, 9, 980049)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilePics/Portrait.png', null=True, upload_to='profilePics\\<django.db.models.query_utils.DeferredAttribute object at 0x000002503D1D3980>'),
        ),
    ]
