# Generated by Django 5.1.4 on 2024-12-21 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0030_alter_post_image_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 12, 16, 33, 808875)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 12, 16, 33, 808875)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilePics/Portrait.png', null=True, upload_to='profilePics\\<django.db.models.query_utils.DeferredAttribute object at 0x000001AE8F28B980>'),
        ),
    ]
