# Generated by Django 5.1.4 on 2024-12-22 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0042_alter_post_image_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postPics\\2024\\12\\22\\11\\32\\13\\889087'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 11, 32, 13, 889087)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 11, 32, 13, 889087)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='profilePics/blank-profile.png', upload_to='profilePics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, default='profilePics/blank-profile.png', null=True, upload_to='profilePics\\2024\\12\\22'),
        ),
    ]
