# Generated by Django 5.1.4 on 2024-12-22 19:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0043_alter_post_image_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeckWebApp.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postPics\\2024\\12\\22\\12\\39\\20\\404950'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 12, 39, 20, 404950)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 12, 39, 20, 404950)),
        ),
    ]
