# Generated by Django 5.1.4 on 2024-12-22 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeckWebApp', '0046_post_creator_name_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postPics\\2024\\12\\22\\14\\55\\48\\279920'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 14, 55, 48, 279920)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 14, 55, 48, 279920)),
        ),
    ]
